version: '3.8'

services:
  infositel:
    build: .
    container_name: infositel_web
    restart: always
    ports:
      - "3000:3000"
    volumes:
      - infositel_uploads:/app/public/uploads
      - infositel_db:/app/prisma
    env_file:
      - .env
    environment:
      - NODE_ENV=production
      - HOSTNAME=0.0.0.0

volumes:
  infositel_uploads:
  infositel_db:
